# Generated by Django 5.0.6 on 2025-09-12 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_announcement_financialfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del área')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad de personas')),
                ('booking_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por reserva')),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('common_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.commonarea', verbose_name='Área común')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-start_time'],
            },
        ),
    ]
