# Generated by Django 5.0.6 on 2025-09-12 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_commonarea_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la mascota')),
                ('species', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Pez', 'Pez'), ('Otro', 'Otro')], max_length=20, verbose_name='Especie')),
                ('breed', models.CharField(max_length=50, verbose_name='Raza')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad (años)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True, verbose_name='Placa del vehículo')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100, verbose_name='Nombre del visitante')),
                ('visitor_dni', models.CharField(max_length=20, verbose_name='DNI/Identificación')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de entrada')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('vehicle_license_plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa del vehículo')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Salió', 'Salió')], default='Activo', max_length=20, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to=settings.AUTH_USER_MODEL, verbose_name='Residente visitado')),
            ],
            options={
                'verbose_name': 'Registro de Visitante',
                'verbose_name_plural': 'Registros de Visitantes',
                'ordering': ['-entry_time'],
            },
        ),
    ]
