# Generated by Django 5.0.6 on 2025-09-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_feedback_paymenttransaction_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='visitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/', verbose_name='Foto del Visitante'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
