# Generated by Django 5.0.6 on 2025-09-26 20:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_visitorlog_visitor_photo_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='visitor_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto del Visitante'),
        ),
    ]
